### ISSUE TITLE
Put to submenu

### ISSUE THREAD

**Issue by majidempire** [AloPeyk/AloPeyk-WooCommerce-Plugin#17]
Add an option that allows user to put Alopeyk menu from root to "Woocommerce" menu , it is unnecessary that Alopeyk menu is on wordpress root

**Comment by bijanmoudi** [comment]
Thanks for your feedback.
Since we plan to add more features to Alopeyk's ecosystem which are not so related to the WooCommerce functionality, we've added the Alopeyk option to root-level menu.
But we will forward your opinion to the decision makers.
